name: code scanning

on:
  pull_request:
  schedule:
    - cron: 0 1 * * 4

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize
        uses: github/codeql-action/init@v2
        with:
          languages: go

      - name: Analyze
        uses: github/codeql-action/analyze@v2